// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoxjhbgcfffghjzncwlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhveGpoYmdjZmZmZ2hqem5jd2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MjMwMTUsImV4cCI6MjA1Mzk5OTAxNX0.hUhAjqIk_j2K6jeEdFfD6fkPgYcceBsbESS0Ywp4bEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);